<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_hobbies</name>
   <tag></tag>
   <elementGuidId>8884c6ab-c110-435a-8858-032f0986e03b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inputDescriptionHobbies']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputDescriptionHobbies</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dc316761-cb82-4c61-8981-cb7257e2bac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3f5b619d-0fb6-4acf-b76f-3036c90222af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0754b79a-3a6b-4509-81dd-7c185a01f620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>3aede92f-4277-4189-9bb7-53b2dd866933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputDescriptionHobbies</value>
      <webElementGuid>198c243c-ffe2-4bb7-a40e-5ac3805b5e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>You can add or delete your information</value>
      <webElementGuid>f98496c8-a408-4392-a90b-59147c58dd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hobbies</value>
      <webElementGuid>b07fe7f2-0003-4e5c-bf95-adcee53d2050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputDescriptionHobbies&quot;)</value>
      <webElementGuid>551e7fa6-17a7-4b10-bad6-b09b72155cad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inputDescriptionHobbies']</value>
      <webElementGuid>b85216a3-ff63-42ed-a0ff-c2455e24b454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container-category']/form/div/div[2]/div/div[2]/textarea</value>
      <webElementGuid>9f13e0b5-ef68-436f-ba41-fa9927d1a772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/textarea</value>
      <webElementGuid>13366f98-17ec-4157-bac8-c15bb71448b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'inputDescriptionHobbies' and @placeholder = 'You can add or delete your information' and @name = 'hobbies']</value>
      <webElementGuid>83033c5f-7d0a-47fc-8353-107abadc87c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
