<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_datadriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>11965050-4845-4885-8d11-2cbad328946f</testSuiteGuid>
   <testCaseLink>
      <guid>84234255-c7e7-40dc-9ac1-b174c697b164</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Senior_Testcase/Senior_Login/TC-02_Login_datadriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8a546a34-2e24-4fbd-88e1-79bf6a5ee946</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Senior_Login_data/Login_data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8a546a34-2e24-4fbd-88e1-79bf6a5ee946</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>a9151d1b-97db-4edc-833d-6810a8e6e68d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8a546a34-2e24-4fbd-88e1-79bf6a5ee946</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>f67825d1-6c85-4d1c-8d04-757e2ad3af0a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
