<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__zipcode</name>
   <tag></tag>
   <elementGuidId>87438566-d117-48fc-bd82-0700b236fed1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputzipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputzipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e6ce291-0135-4000-a051-481b886191a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input </value>
      <webElementGuid>f06a1289-bfe3-492a-9786-5808beac2af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputzipcode</value>
      <webElementGuid>dbe013e6-2ca9-49f6-ab05-7ce9cfc695fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6347cd6-72f6-4261-b7a7-14b453d32bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>be7f3c6c-9207-40ab-8d1f-29fb6e59d106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter ZIP code of your location</value>
      <webElementGuid>9b05c8ec-1fab-41a6-87cd-3cb83af66e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputzipcode&quot;)</value>
      <webElementGuid>f13f67df-d706-49fd-9f43-87cfdccc96ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputzipcode']</value>
      <webElementGuid>7e767528-553c-4a2c-914b-5c6bf15f63da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>2d39f2d5-6091-4c39-9162-b02ac8e505f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ca8bebe2-4b96-46bb-a420-a3c0b1f77fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputzipcode' and @type = 'text' and @name = 'zipcode' and @placeholder = 'Enter ZIP code of your location']</value>
      <webElementGuid>4ad9ec32-b83d-4893-b2f2-72219b9cce2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
