<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__role</name>
   <tag></tag>
   <elementGuidId>574b08f0-517f-43a1-8a9c-793e4a5b4521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputrolesenior</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputrolesenior']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fff2c540-5a0f-4e8b-ab1d-d400365c2c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input-role </value>
      <webElementGuid>7408f32d-17cd-4baf-9259-49612999aadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputrolesenior</value>
      <webElementGuid>23bf0920-a4b5-4e12-a1ef-442feb1c5e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>8660200c-a1c5-4299-bc2b-c6a29ea34017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ae4d8724-fb1d-41b3-b950-813bec8db3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Senior</value>
      <webElementGuid>91388b38-9431-4e81-abbc-3f1e90ce1e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputrolesenior&quot;)</value>
      <webElementGuid>96532f8a-cf38-4b4d-a384-ed2961f297e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputrolesenior']</value>
      <webElementGuid>ecb6de92-ec91-4899-916c-d67edcfe289e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[5]/div/div/input</value>
      <webElementGuid>ab553d81-eb9f-43f0-af63-7a2c121ce5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>97e911ba-bdb5-4152-848d-9d588931687f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputrolesenior' and @name = 'role' and @type = 'radio']</value>
      <webElementGuid>bdb23300-3829-453e-87a9-181aa217bb3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
