<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_zipcode</name>
   <tag></tag>
   <elementGuidId>7cca511a-9731-4880-87a8-b4a7ec671d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputzipcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputzipcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a77e148-3b62-4c08-b14a-60e89d5378bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input </value>
      <webElementGuid>f931a64e-00c2-4126-bb51-c6ca9842ed3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputzipcode</value>
      <webElementGuid>05da8bff-668a-41b3-992d-7398a3556c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f39cb71-c00c-42d0-b8b7-737db7097edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>1f27cdf3-47c0-44b7-8d8d-1a69712b5cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter ZIP code of your location</value>
      <webElementGuid>b48ed1e8-2785-4341-9470-753d47ae9312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputzipcode&quot;)</value>
      <webElementGuid>6c79d062-05e5-45e3-8aa0-e912c5dda7cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputzipcode']</value>
      <webElementGuid>ce3ef8e7-ad5c-4d57-b266-707caccade53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>6f5025c7-f87a-4da3-9cab-339d1fa8a3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e7fc1b27-48bc-43a3-a0e6-db4ca89e8e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputzipcode' and @type = 'text' and @name = 'zipcode' and @placeholder = 'Enter ZIP code of your location']</value>
      <webElementGuid>c9e3749a-498d-4dfc-879a-0e1dda352e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
